{{- if not .Values.externalSecrets.enabled }}
{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "claimTxPrivateKeyPassword") }}
        {{- $claimTxPrivateKeyPassword = index $opSecrets.data "claimTxPrivateKeyPassword" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "l1RpcURL") }}
        {{- $l1RpcURL = index $opSecrets.data "l1RpcURL" | b64dec }}
    {{- end }}

    {{- if (index $opSecrets.data "bridgeDbName") }}
        {{- $bridgeDbName = index $opSecrets.data "bridgeDbName" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbUser") }}
        {{- $dbUser = index $opSecrets.data "dbUser" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbUserPassword") }}
        {{- $dbUserPassword = index $opSecrets.data "dbUserPassword" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbHost") }}
        {{- $dbHost = index $opSecrets.data "dbHost" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbPort") }}
        {{- $dbPort = index $opSecrets.data "dbPort" | b64dec }}
    {{- end }}
{{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  bridge-config.toml: |
    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]

    [SyncDB]
    Database = "postgres"
      [SyncDB.PgStorage]
      # Database credentials will be injected via environment variables
      User = "${DB_USER}"
      Password = "${DB_USER_PASSWORD}"
      Name = "${BRIDGE_DB_NAME}"
      Host = "${DB_HOST}"
      Port = "${DB_PORT}"
      MaxConns = 200

    [Etherman]
    # L1 RPC URL will be injected via environment variable
    l1URL = "${L1_RPC_URL}"
    L2URLs = [{{ .Values.config.etherman.l2Url | quote }}]

    [Synchronizer]
    SyncInterval = "5s"
    SyncChunkSize = 1000
    ForceL2SyncChunk = {{ .Values.config.synchronizer.forceL2SyncChunk }}

    [BridgeController]
    Store = "postgres"
    Height = 32

    [BridgeServer]
    CacheSize = 100000
    GRPCPort = "9090"
    HTTPPort = "8080"
    DefaultPageLimit = 25
    MaxPageLimit = 100
    BridgeVersion = "v1"
    FinalizedGEREnabled = {{ .Values.config.bridgeServer.finalizedGEREnabled }}

    [BridgeServer.DB]
    Database = "postgres"
      [BridgeServer.DB.PgStorage]
      # Database credentials will be injected via environment variables
      User = "${DB_USER}"
      Password = "${DB_USER_PASSWORD}"
      Name = "${BRIDGE_DB_NAME}"
      Host = "${DB_HOST}"
      Port = "${DB_PORT}"
      MaxConns = 200

    [NetworkConfig]
    L1GenBlockNumber = {{ .Values.config.network.l1GenBlockNumber | int64 }}
    PolygonBridgeAddress = {{ .Values.config.network.polygonBridgeAddress | quote }}
    PolygonZkEVMGlobalExitRootAddress = {{ .Values.config.network.polygonZkEVMGlobalExitRootAddress | quote }}
    PolygonRollupManagerAddress = {{ .Values.config.network.polygonRollupManagerAddress | quote }}
    PolygonZkEVMAddress = {{ .Values.config.network.polygonZkEVMAddress | quote }}
    L2PolygonBridgeAddresses = [{{ .Values.config.network.l2PolygonBridgeAddress | quote }}]
    L2PolygonZkEVMGlobalExitRootAddresses = [{{ .Values.config.network.l2PolygonZkEVMGlobalExitRootAddress | quote }}]
    L2GenBlockNumbers = [{{ .Values.config.network.l2GenBlockNumbers | int64 }}]
    RequireSovereignChainSmcs = [{{ .Values.config.network.requireSovereignChainSmcs }}]

    [ClaimTxManager]
    FrequencyToMonitorTxs = "5s"
    # Keystore password will be injected via environment variable
    PrivateKey = {Path = {{ .Values.config.claimTxManager.path | quote }}, Password = "${CLAIM_TX_PRIVATE_KEY_PASSWORD}"}
    Enabled = true
    RetryInterval = "1s"
    AreClaimsBetweenL2sEnabled = {{ .Values.config.claimTxManager.areClaimsBetweenL2sEnabled }}
