{{- if and (not .Values.externalSecrets.enabled) .Values.ingress.enabled .Values.tls.createSecret (not .Values.tls.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agglayer.fullname" . }}-cloudflare-origin-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.base64Cert }}
  tls.key: {{ .Values.tls.base64Key }}
{{- end }}