{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: agglayer-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl ((.Files.Glob "config/config.toml").AsConfig | indent 2) . }}
{{- end }}
