{{- if and (not .Values.externalSecrets.enabled) .Values.gke.enabled .Values.gke.backendConfig.enabled }}
{{- $clientID := "" }}
{{- $clientSecret := "" }}
{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
{{- if and $opSecrets $opSecrets.data }}
    {{- if (index $opSecrets.data "admin_api_oauth_client_id") }}
        {{- $clientID = index $opSecrets.data "admin_api_oauth_client_id" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "admin_api_oauth_client_secret") }}
        {{- $clientSecret = index $opSecrets.data "admin_api_oauth_client_secret" | b64dec }}
    {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agglayer.name" . }}-admin-oauth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client_id: {{ $clientID | quote }}
  client_secret: {{ $clientSecret | quote }}
{{- end }}