apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "agglayer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agglayer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agglayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if .Values.gke.enabled }}
        # https://cloud.google.com/kubernetes-engine/docs/how-to/extended-duration-pods
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        {{- end }}
        {{- if eq .Values.backup.type "gcsfuse" }}
        # https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/ephemeral-storage-limit: 1Gi
        {{- end }}
        {{- if .Values.datadog.enabled }}
        ad.datadoghq.com/{{ .Chart.Name }}.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:{{ .Values.ports.telemetry }}/metrics",
                  "namespace": "agglayer",
                  "metrics": [".*"]
                }
              ]
            }
          }
        {{- end }}
      labels:
        {{- include "agglayer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agglayer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - agglayer
            - run
          args:
            - "--cfg"
            - "/etc/agglayer/config.toml"
          ports:
            - containerPort: {{ .Values.ports.grpc }}
            - containerPort: {{ .Values.ports.readrpc }}
            - containerPort: {{ .Values.ports.admin }}
            - containerPort: {{ .Values.ports.telemetry }}
          # TMP: disabling probes for now as the new version doesn't expose API until it's synced with l1
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.ports.grpc }}
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.ports.grpc }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/etc/agglayer"
              name: config
              readOnly: true
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
            {{- if ne .Values.backup.type "none" }}
            - name: backup
              mountPath: {{ .Values.backup.path | quote }}
              readOnly: false
            {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: agglayer-config
                items:
                  - key: "config.toml"
                    path: "config.toml"
            {{- if eq .Values.aggregator.keyName "" }}
            - secret:
                name: {{ .Values.existingSecret }}
                items:
                  - key: {{ .Values.aggregator.keystoreFileName }}
                    path: {{ .Values.aggregator.keystoreFileName }}
            {{- end }}
        {{- if eq .Values.storage.type "hostPath" }}
        - name: data
          hostPath:
            path: {{ .Values.storage.hostPath | quote }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if ne .Values.backup.type "none" }}
        - name: backup
          {{- if eq .Values.backup.type "hostPath" }}
          hostPath:
            path: {{ .Values.backup.hostPath | quote }}
            type: DirectoryOrCreate
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "agglayer.fullname" . }}-backup-pvc
            readOnly: false
          {{- end }}
        {{- end }}
  {{- if eq .Values.storage.type "pvc" }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName | quote }}
        {{- else if .Values.storageClass.create }}
        storageClassName: {{ default (include "agglayer.fullname" .) .Values.storageClass.name }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
  {{- end }}
