# For use in clusters with the 1P operator
# onePasswordSecrets:
#   <name>: <item-path>

# Used as a backwards-compatible stopgap to do environment interpolation in the config until the aggkit supports config from the environment
mountRawConfig: true

env: bali
metadata:
  service: aggkit

podLabels:
  name: myname
  business_unit: agglayer
  role: myrole
  partner: Polygon
  network: mynetwork

existingSecret: op-secrets

nodeSelector: {}

tolerations: []

initContainers: []

extraVolumes: []

topologySpreadConstraints: []

replicas: 1

container:
  extraVolumeMounts: []

  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/agglayer/aggkit
    tag: latest

  ports:
    aggsender: 5576
    bridge: 5577
    validator: 5578 # named validator as is common to aggsender and aggsender-validator
    prometheus: 9091

service:
  type: ClusterIP
  clusterIP: None

ingresses:
  aggsender:
    create: false
    hostname: "something.dev.polygon"
  bridge:
    create: false
    hostname: "something-else.dev.polygon"
  aggsenderValidator:
    create: false
    hostname: "something-else-else.dev.polygon"

httpRoutes:
  aggsenderValidator:
    create: false
    hostname: domain.example
    parentRef:
      name: gateway
      namespace: gateways

serviceAccount:
  create: false
  annotations: {}

storage:
  path: /data
  size: 50Gi

podSecurityContext: {}
securityContext: {}

config:
  # list of components: aggsender, aggsender-validator, aggoracle, bridge
  components:
    - aggsender
    - aggoracle

  aggsender:
    certificateSendInterval: 1m
    checkSettledInterval: 5s
    checkStatusCertificateInterval: 5m
    dryRun: false
    maxCertSize: 8388608
    maxL2BlockNumber: 0
    mode: "AggchainProof" # PessimisticProof (PP) or AggchainProof (FEP)
    retryCertAfterInError: false
    saveCertificatesToFilesPath: /tmp

    # Set this if aggsender.mode is AggchainProof
    aggkitProverClient:
      url: "http://aggkit-prover:4446"
      useTLS: true

    agglayerClient:
      url: "http://agglayer:4444"
      useTLS: true

    validatorClient:
      url: "http://localhost:5578"
      useTLS: false

    privateKey:
      keyName: "" # if this string is not empty, aggsender will try to use KMS
      keystoreFileName: "aggsender.keystore"
      keystoreFilePasswordSecretFieldName: "aggsenderKeystorePassword"

    optimisticModeEnabled: false

  aggsenderValidator:
    mode: "PessimisticProof" # PessimisticProof (PP) or AggchainProof (FEP)

    agglayerClient:
      url: "http://agglayer:4444"
      useTLS: true

    privateKey:
      keyName: "" # if this string is not empty, aggsender-validator will try to use KMS
      keystoreFileName: "aggsenderValidator.keystore"
      keystoreFilePasswordSecretFieldName: "aggsenderValidatorKeystorePassword"

  aggoracle:
    enableAggoracleCommittee: true
    aggoracleCommitteeAddr: "0x"

    privateKey:
      keyName: "" # if this string is not empty, aggoracle will try to use KMS
      keystoreFileName: "aggoracle.keystore"
      keystoreFilePasswordSecretFieldName: "aggoracleKeystorePassword"

  l1InfoTreeSync:
    blockFinality: "FinalizedBlock" # "LatestBlock/-6" for fast L1 deposits

  reorgDetectorL1:
    blockFinality: "FinalizedBlock"

  bridgeL1Sync:
    blockFinality: "LatestBlock" # "LatestBlock/-6" for fast L1 deposits
    initialBlockNum: 0

  reorgDetectorL2:
    blockFinality: "LatestBlock"

  bridgeL2Sync:
    blockFinality: "LatestBlock"

  l2GERSync:
    blockFinality: "LatestBlock"

  l1:
    bridgeAddress: "0x96dE011d4f794ADAe25E6dF8F927EE71A7E58e76"
    chainId: 11155111
    globalExitRootAddress: "0x1C889784Eb6873d43461a823DFb0Aa8E0e11DB6F"
    polTokenAddress: "0xb6eFF1F58BDc08D032b74Da39512d90b1Db6263a"
    rollupAddress: "0x8b86B44C6Ad3ac1e7481f0B26D1BDbd86A4dd92f"
    rollupBlockNumber: "231"
    rollupManagerAddress: "0x1D6fd904917fD52492c3A6E8d8d6829c288014E5"
    rollupManagerBlockNumber: 30
    syncBlockChunkSize: 1000

  l2:
    agglayerAddress: "0x123"
    bridgeAddress: "0x96dE011d4f794ADAe25E6dF8F927EE71A7E58e76"
    chainId: 3
    globalExitRootAddress: "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa"
    rpcURL: http://op-succinct-sequencer.op-succinct.svc.cluster.local:8545
    opNodeURL: http://op-succinct-sequencer.op-succinct.svc.cluster.local:9545
    initialBlockNum: 0

  log:
    environment: development # "production" or "development"
    level: info

  prometheus:
    enabled: true
    host: 0.0.0.0

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 1
    memory: 4Gi

# GKE-specific health check policy (networking.gke.io/HealthCheckPolicy)
healthCheckPolicy:
  enabled: true
