{{- if and (not .Values.externalSecrets.enabled) .Values.onePasswordSecrets }}
{{- range $name, $path := .Values.onePasswordSecrets }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $name }}
spec:
  itemPath: {{ $path }}
{{- end }}
{{- end }}
