# Example values file for a DEV environment
# Copy to values.dev.yaml and adjust.

env: dev

container:
  replicaCount: 1
  env:
    networkRpcUrl: "https://rpc.succinct.xyz/"

  # Optional overrides
  # image:
  #   tag: "0.4.4"

resources:
  limits:
    cpu: 32
    memory: 36Gi
  requests:
    cpu: 30
    memory: 30Gi
