env: bali

podLabels:
  name: agglayer-prover
  business_unit: agglayer
  role: agglayer-node
  partner: Polygon

container:
  image:
    repository: ghcr.io/agglayer/agglayer
    pullPolicy: IfNotPresent
    tag: 0.4.4
  
  ports:
    app: 4445
    telemetry: 9092

  replicaCount: 1

  env:
    networkRpcUrl: https://rpc.succinct.xyz/

podAnnotations: {}

resources:
  limits:
    cpu: 36
    memory: 40Gi
  requests:
    cpu: 32
    memory: 30Gi

# Probes (override per-environment as needed)
startupProbe:
  grpc:
    port: 4445
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 30

readinessProbe:
  grpc:
    port: 4445
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  grpc:
    port: 4445
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

config:
  maxConcurrencyLimit: 100
  maxRequestDuration: 300
  maxBufferedQueries: 100

  log:
    environment: development # "production" or "development"
    level: debug
    format: "pretty"

  networkProver:
    enabled: false
    provingTimeout: "30m"
    provingRequestTimeout: "10m"
  
  grpc:
    # size is define in bytes e.g. 100 * 1024 * 1024
    # same for `max-encoding-message-size`
    # default value is equal to 4MB
    maxDecodingMessageSize: 104857600
  
  cpuProver:
    enabled: true
    maxConcurrencyLimit: 100
    provingTimeout: "60m"

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
