env: dev

backendConfig:
  enabled: false

config:
  log:
    environment: development # "production" or "development"
    level: info
  bridgeServer:
    finalizedGEREnabled: true
  claimTxManager:
    path: /etc/bridge/claimtx.keystore
    areClaimsBetweenL2sEnabled: true
  network:
    l1GenBlockNumber: 177360
    polygonBridgeAddress: "0xbE31765BBD2cf1cb7018F6D047ffC02cbd727f59"
    polygonZkEVMGlobalExitRootAddress: "0x9d35296Df31AD86cF1e7e6b39100396328511522"
    polygonRollupManagerAddress: "0xbD2CC252599B1216EE5a202ce1fD2e19835739a0"
    polygonZkEVMAddress: "0x603C86D91ca3085D7BcFF099533A8835692E65BE"
    l2GenBlockNumbers: 0
    l2PolygonBridgeAddress: "0xbE31765BBD2cf1cb7018F6D047ffC02cbd727f59"
    l2PolygonZkEVMGlobalExitRootAddress: "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa"
    requireSovereignChainSmcs: true
  synchronizer:
    forceL2SyncChunk: true