env: bali

podLabels:
  name: myname
  business_unit: agglayer
  role: myrole
  partner: Polygon
  network: mynetwork

replicaCount: 1

image:
  repository: ghcr.io/0xpolygon/zkevm-bridge-service
  pullPolicy: IfNotPresent
  tag: "v0.6.3-RC4"
  command: ["/app/zkevm-bridge"]
  args: ["run", "--cfg", "/etc/bridge/bridge-config.toml"]

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  hostname: something.dev.polygon

resources:
  limits:
    memory: 1G
  requests:
    cpu: 1
    memory: 512M

# GKE-specific BackendConfig healthcheck (cloud.google.com/BackendConfig)
backendConfig:
  enabled: true

config:
  log:
    environment: development # "production" or "development"
    level: info
  bridgeServer:
    finalizedGEREnabled: true
  etherman:
    l2Url: "http://op-geth.op-succinct-l2.svc.cluster.local:8123"
  claimTxManager:
    path: /etc/bridge/claimtx.keystore
    areClaimsBetweenL2sEnabled: false
  network:
    l1GenBlockNumber: 0
    polygonBridgeAddress: "0x0000000000000000000000000000000000000000"
    polygonZkEVMGlobalExitRootAddress: "0x0000000000000000000000000000000000000000"
    polygonRollupManagerAddress: "0x0000000000000000000000000000000000000000"
    polygonZkEVMAddress: "0x0000000000000000000000000000000000000000"
    l2GenBlockNumbers: 0
    l2PolygonBridgeAddress: "0x0000000000000000000000000000000000000000"
    l2PolygonZkEVMGlobalExitRootAddress: "0x0000000000000000000000000000000000000000"
    requireSovereignChainSmcs: true
  synchronizer:
    forceL2SyncChunk: true

existingSecret: "op-secrets"
secretItem:
  key: "claimtx.keystore"
  path: "claimtx.keystore"
