env: dev

image:
  tag: "1.8.0"

config:
  networkId: 3
  mock: false
  polygonRollupManager: "0x1D6fd904917fD52492c3A6E8d8d6829c288014E5"
  globalExitRootManagerV2SovereignChain: "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa"
  genesis: |
    {
      "config": {
        "chainId": 2027,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "arrowGlacierBlock": 0,
        "grayGlacierBlock": 0,
        "mergeNetsplitBlock": 0,
        "shanghaiTime": 0,
        "cancunTime": 0,
        "pragueTime": 0,
        "bedrockBlock": 0,
        "regolithTime": 0,
        "canyonTime": 0,
        "ecotoneTime": 0,
        "fjordTime": 0,
        "graniteTime": 0,
        "holoceneTime": 0,
        "isthmusTime": 0,
        "terminalTotalDifficulty": 0,
        "depositContractAddress": "0x0000000000000000000000000000000000000000",
        "optimism": {
          "eip1559Elasticity": 6,
          "eip1559Denominator": 50,
          "eip1559DenominatorCanyon": 250
        }
      }
    }


datadir:
  path: /data
  size: 50Gi

serviceAccount:
  create: false
